import { Metadata } from 'next'

import { MarketingPageShell } from '@/features/landing/components/marketing-page-shell'
import { CONTACT_MAILTO } from '@/lib/contact-info'
import {
  marketingLegalHeadingClassName,
  marketingLegalLinkClassName,
  marketingLegalMutedClassName,
} from '@/lib/styles/marketing-styles'

export const metadata: Metadata = {
  title: 'Terms & Conditions | AI Interview Trainer',
  description: 'Terms and conditions for using AI Interview Trainer',
}

export default function TermsPage() {
  return (
    <MarketingPageShell title="Terms & Conditions">
      <p className={marketingLegalMutedClassName}>Last updated: June 2026</p>
      <p>
        By using AI Interview Trainer, you agree to these terms. The platform
        provides AI-assisted interview preparation tools for educational and
        professional use.
      </p>
      <h2 className={marketingLegalHeadingClassName}>Use of Service</h2>
      <p>
        You must provide accurate account information and use the service
        responsibly. Do not misuse the platform, attempt unauthorized access, or
        share content that violates applicable laws.
      </p>
      <h2 className={marketingLegalHeadingClassName}>AI-Generated Content</h2>
      <p>
        Coaching, feedback, and interview responses are generated by AI and are
        provided for practice purposes only. They do not guarantee employment
        outcomes.
      </p>
      <h2 className={marketingLegalHeadingClassName}>Account & Data</h2>
      <p>
        You are responsible for maintaining the security of your account. We
        process your data as described in our Privacy Policy.
      </p>
      <h2 className={marketingLegalHeadingClassName}>Contact</h2>
      <p>
        Questions about these terms? Reach us through our{' '}
        <a href={CONTACT_MAILTO} className={marketingLegalLinkClassName}>
          Contact Us
        </a>{' '}
        page.
      </p>
    </MarketingPageShell>
  )
}
